### ISSUE TITLE
config.php or twig.php

### ISSUE THREAD

**Issue by joemaller** [rcrowe/TwigBridge#169]
The documentation refers to the configuration file as `config.php` but the src directory contains and artisan generates a `twig.php` file instead. I looked, but I didn't quickly turn up a commit where that change happened, so I wanted to confirm before editing the Readme. Is `config.php` now `twig.php`? 

I've been using TwigBridge for a long time, so I had a config.php file still hanging around. If the name change is causing those files to be ignored, that should probably be mentioned as well.

**Comment by mikevrind** [comment]
For L5 you should use the ConfigServiceProvider to overwrite a package default's configuration.
Twigbridge is using 2 different config files which you need to use in this ServiceProvider:

```php
class ConfigServiceProvider extends ServiceProvider
{

	/**
	 * Overwrite any vendor / package configuration.
	 *
	 * This service provider is intended to provide a convenient location for you
	 * to overwrite any "vendor" or package configuration that you may want to
	 * modify before the application handles the incoming request / command.
	 *
	 * @return void
	 */
	public function register()
	{
		config( [

			'twigbridge' => [ // Name of the package
				'twig' => [ // Name of the config file
					'extension' => 'tpl',
				]

			],

		] );
	}

}
```

**Comment by joemaller** [comment]
Laravel might not be getting simpler/easier. :worried: 

The main point of *this* issue is that the TwigBridge documentation ([README.md:48](https://github.com/rcrowe/TwigBridge/blame/master/README.md#L48)) references a file that's apparently been renamed/deprecated since last July.

**Comment by mikevrind** [comment]
I agree on that. I find this setup verry confusing.

But there indeed is a mistake in the readme about the config file(s).

**Comment by barryvdh** [comment]
Tweaked the readme a bit.

**Comment by mikeerickson** [comment]
Where are these items to be placed?   

Twig::addExtension('TwigBridge\Extension\Loader\Functions');
Twig::render('mytemplate', $data);

**Comment by rcrowe** [comment]
In another provider?

**Comment by angelov** [comment]
I have a problem when I try to overwrite some of the default config values. As @mikevrind said here, I have this in my ConfigServiceProvider:

```php
        config([
            'twigbridge' => [
                "extensions" => [
                    "facades" => ["Config"],
                ],
            ]
        ]);
```

but after I do this, the system cannot find my view files (InvalidArgumentException in FileViewFinder.php).

Also, now when I try to use the `twig:lint` command, it gives me `0/0 valid files` (if I don't use the stuff in the provider it gives me that all view files are valid).

**Comment by barryvdh** [comment]
Can you setting the config with dots instead of this array form?

**Comment by barryvdh** [comment]
We could perhaps better merge the two files to a 'twigbridge' file, so it's easier to publish.

**Comment by barryvdh** [comment]
See https://github.com/rcrowe/TwigBridge/commit/e7360d742a9490bb902024d71d264f103badc16a
You can now publish/copy the twigbridge.php file to your config folder and make changes there.

Or with the config, probably something like this would be better:

        config([
            'twigbridge.extensions.facades' =>  ["Config"],
        ]);

Otherwise it would cause problems with merging the arrays.

**Comment by angelov** [comment]
Great. Thank you.

**Comment by kaidesu** [comment]
With that update you referenced @barryvdh , is this issue now resolved?

**Comment by barryvdh** [comment]
Think so
