### ISSUE TITLE
Is this working for Laravel 5 yet?

### ISSUE THREAD

**Issue by mayrop** [rcrowe/TwigBridge#178]
I'm requiring this from "rcrowe/twigbridge": "0.7.x-dev"
Adding the service provider & facade... but it seems it doesn't load the views (neither .twig or .twig.php)... 

I keep getting:
```exception 'InvalidArgumentException' with message 'View [test] not found.'```

Any ideas?

**Comment by GrahamCampbell** [comment]
That's not the correct require statement. You want `"rcrowe/twigbridge": "0.7.*@dev"`.

**Comment by mayrop** [comment]
So stupid.. I tried that too... and others.. (from a clean install)... and still is not loading the views :(

**Comment by GrahamCampbell** [comment]
`resources/views` is the default.

**Comment by mayrop** [comment]
Figured it out.. sorry for the inconvenience.. it was wrong env settings.
