### ISSUE TITLE
How could Call a View, using helper?

### ISSUE THREAD

**Issue by Mangulomx** [rcrowe/TwigBridge#192]
I´m using make::view for call to one view
My views are: login.twig, logout.twig

```
 {% if Auth.check() %}
                        <li><a href="{{ View::make('logout') }}">Salir</a></li>
                    {% else %}
                        <li><a href="{{ View::make('login') }}">Entrar</a></li>
                    {% endif %}
```

I don´t found the helper, It being url.to('login') ?

**Comment by barryvdh** [comment]
Sorry, please try to learn the basics before opening all theses issues.

The Facades are explained in the [readme](https://github.com/rcrowe/TwigBridge#facadeloader):
> To use the Laravel integration (or indeed any aliased class and method), just add your facades to the config and call them like URL.to(link) (instead of URL::to($link))

The helper functions are also mentioned (`url()`, `action()`, `route()` etc). 

`View::make` is used to render a view, not to create a link..
