### ISSUE TITLE
Get error 'Call to undefined method setName()

### ISSUE THREAD

**Issue by tsdevelopment** [rcrowe/TwigBridge#193]
Hi there,

I want to use a custom extension for my views (.twig.html). But if I set the config parameter in the 'ConfigServiceProvider' I get the following error:

```
Call to undefined method __TwigTemplate_8abbbc578c3c617c791ad8adf49bc52d84bdba211d0178ecd1ba687d7b967f89::setName()
```

If I set the extension to '.twig' everything works fine. The error occures also if I use '.html' (or .php) as extension. What's wrong with my Code?

Content of 'app/Providers/ConfigServiceProvider.php':

``` php
public function register()
{
    config([
        'twigbridge' => [
            'twig' => [
                'extension' => 'twig.html',
            ],
        ],
    ]);
}
```

I am  using Laravel 5.0.\* (current stable release).

**Comment by samwilson** [comment]
I'm getting this same error (with a very similar config).

**Comment by barryvdh** [comment]
Probably because the Laravel loader doesn't recognize it. Might need a check for the instanceof the template.
