### ISSUE TITLE
TwigBridge and Lumen?

### ISSUE THREAD

**Issue by cviebrock** [rcrowe/TwigBridge#195]
Just wondering if you've looked at making a [Lumen](http://lumen.laravel.com/)-compatible version of TwigBridge?

**Comment by barryvdh** [comment]
Not yet.

**Comment by cviebrock** [comment]
Fair enough.  ;)

**Comment by barryvdh** [comment]
But we're open to PR's ;)

**Comment by barryvdh** [comment]
Should be fixed, see https://github.com/rcrowe/TwigBridge#installation-on-lumen and #198

**Comment by cviebrock** [comment]
:D. Thanks!
