### ISSUE TITLE
View composers for layouts and included views not firing

### ISSUE THREAD

**Issue by Anahkiasen** [rcrowe/TwigBridge#202]
I'm using TwigBridge on Laravel 5 (0.7.2), I'm having an issue with view composers. More precisely view composers for layouts and included views are never fired, while composers for directly rendered views (View::make, etc) work properly.

I double checked, all my path separators are unified to `/`, so it can't be like the bug in previous versions where using dots and slashes in unison would cause composers to not fire.

Do I need to place the view composers somewhere in particular or something? Currently in my `AppProvider::boot` method

**Comment by barryvdh** [comment]
Is nothing fired, or wrong events fired?
Can you check all events, to see if we're passing the wrong name or something? (dots vs slashes, with/without .twig)

**Comment by Anahkiasen** [comment]
That's the weird part, the composing event is fired, but the method itself isn't called:

```php
$this->app['view']->composers([
    LayoutComposer::class.'@composeNavigation' => '_layouts/main',
]);
```

```
creating: _layouts/main (0μs)
composing: _layouts/main (0μs)
```

If I put per example `dd('test');` in `LayoutComposer::composeNavigation`, that never gets fired, nor does it appear anywhere in the source.

**Comment by Anahkiasen** [comment]
Any news on this one?

**Comment by Anahkiasen** [comment]
Ok so I dig into the code, the issue is that when the composer is registered the name is normalized, so `composing: _layouts/main` is normalized to `composing: _layouts.main` [here](https://github.com/laravel/framework/blob/5.1/src/Illuminate/View/Factory.php#L398)

However when the view is made, while its name its normalized, the name of the includes and partials are not. Take a view:

**test/test.twig**
```twig
{% extends '_layouts/main' %}

{% block content %}{% endblock %}
```

Here are the events that are fired:

```
composing: test.test
composing: _layouts/main
```

**Comment by Anahkiasen** [comment]
Normalizing the name in `Template::fireEvents` fixes the issue but I'm not sure it's the correct place to do that?

```diff
$viewName = $this->name ?: $this->getTemplateName();
+$viewName = str_replace('/', '.', $viewName);
```

**Comment by barryvdh** [comment]
I think we should probably normalize it there indeed.

**Comment by Anahkiasen** [comment]
Aight opened a PR then

**Comment by SCIF** [comment]
@barryvdh:

I extended a view with relative path, ie:

```
{% extends "../layout.twig" %}
```

and event named `composing: ...layout`. I understand that it's probably not covered by name conventions, but it's the single way to get views clickable for me. Will you merge a PR if i implement supporting of relative paths?
