### ISSUE TITLE
PHP 7 Compatibility - 'String' as a class name.

### ISSUE THREAD

**Issue by shehi** [rcrowe/TwigBridge#204]
In a nutshell: 

![image](https://cloud.githubusercontent.com/assets/653569/7911167/a8673414-0863-11e5-9071-3c2295e5bb4d.png)

**Comment by barryvdh** [comment]
Should probably just rename to `Str`. Which would be a bit annoying because everyones config should then change. So would have to be 0.8 (Or we would need to rename/alias it or something)

**Comment by GrahamCampbell** [comment]
Alias would work. phpparser do thiat.

**Comment by shehi** [comment]
Or we can just release new sub-version for PHP-7 compatibility and tag it as such.

**Comment by mikevrind** [comment]
It would be nice to fix this PHP7 issue since the official release is in november.

**Comment by vniko** [comment]
Hi guys!
Just switched to php7 and got the following:
Cannot instantiate Twig extension 'TwigBridge\Extension\Laravel\String': Class TwigBridge\Extension\Laravel\String does not exist

Any help on this?

**Comment by barryvdh** [comment]
Try Str instead of String

**Comment by vniko** [comment]
@barryvdh Thank you, works fine)
