### ISSUE TITLE
@inject  equivalent

### ISSUE THREAD

**Issue by zofe** [rcrowe/TwigBridge#219]
there is an equivalent or a suggested way to inject services as we can do in new @inject  symbol in blade?

as alternative.. it is possible to mix twig and blade   i.e.  main view in twig with a blade  inclusion ?

**Comment by rcrowe** [comment]
You can make use of the `https://github.com/rcrowe/TwigBridge#facadeloader` or create an extension.

**Comment by zofe** [comment]
ok, thanks!
