### ISSUE TITLE
The errors MessageBag from the Validator is always null

### ISSUE THREAD

**Issue by andresnijder** [rcrowe/TwigBridge#223]
i'm trying to retrieve the errors after validation, but the var errors is always null.
Any ideas?

**Comment by andresnijder** [comment]
my bad. in order to retrieve the errors, make sure the following middlewares are use:
Illuminate\Session\Middleware\StartSession::class,
Illuminate\View\Middleware\ShareErrorsFromSession::class,

**Comment by ianspangler** [comment]
I have both of these middlewares defined (by default) in the web group and I am still getting a null {{ errors }} object in my twig template. I am using Laravel 5.2. Any ideas?
