### ISSUE TITLE
[Critical] TwigBridge totally broken (below PHP 7) due to missing new release

### ISSUE THREAD

**Issue by shehi** [rcrowe/TwigBridge#233]
For unit-tests, TwigBridge is completely broken, related to #229 and PR #230 - after merging and closing those issues, I requested for a new release, as currently no unit-test works for anything below PHP 7. This is critical failure guys, please release v0.8.3 asap.

**Comment by Sinius15** [comment]
+1 
Same problem here. 
As a temp workaround, you could change the version from 
``"rcrowe/twigbridge": "0.8.x"``
to
``"rcrowe/twigbridge": "dev-master"``
This tells composer to install the latest commit and ignore the versioning.

**Comment by rcrowe** [comment]
I'm going to tag `0.9.0`.

I'm actively working on the tests. Not just get them passing, completely tearing them up as they were pretty :hankey:

**Comment by rcrowe** [comment]
That's now tagged
