### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by glennjacobs** [rcrowe/TwigBridge#238]
Yep, it's that time again! Could 5.2 compatibility be added?

**Comment by glennjacobs** [comment]
Seems it's the config side of things that's the main issue.

**Comment by barryvdh** [comment]
What's the problem?

**Comment by glennjacobs** [comment]
From what I can see, it's this line in the Service Provider

$this->app['config']->package('rcrowe/twigbridge', __DIR__.'/config');

**Comment by pprins** [comment]
Any update on this?

**Comment by barryvdh** [comment]
Still not sure what the issue is exactly? 
But open for a PR!

**Comment by glennjacobs** [comment]
I believe 5.2 removes the ->package() method. This is strange as I would have thought a minor update should retain backwards compatibility, but Laravel doesn't seem to conform to that way of doing things.

**Comment by barryvdh** [comment]
Laravel indeed doesn't follow SemVer

**Comment by barryvdh** [comment]
And where did you find that line?
Are you on 0.9.x?

**Comment by glennjacobs** [comment]
Hmmmm, strange. Apologies if I'm being dense! :)

Let me try install it again and I'll see what happens.

**Comment by glennjacobs** [comment]
OK, if I used a tagged version it fails. Not sure where my original error came from, doesn't appear to be happening now.

However, using 'dev-master' branch it installs fine. So should there be a tagged version created now for Laravel 5.2?

**Comment by pprins** [comment]
I agree, I have the same. dev-master branch gives me no problems.

**Comment by barryvdh** [comment]
Just tagged v0.9.1
