### ISSUE TITLE
Laravel 5.2 Support?

### ISSUE THREAD

**Issue by ianspangler** [rcrowe/TwigBridge#240]
I'm getting indications when I update composer that TwigBridge isn't compatible with Laravel 5.2. Is this correct? How can I make this work for 5.2?

Problem 1
    - Conclusion: remove laravel/framework v5.2.3
    - Conclusion: don't install laravel/framework v5.2.3
    - rcrowe/twigbridge v0.8.0 requires illuminate/view 5.0.*|5.1.* -> satisfiable by illuminate/view[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8].
    - rcrowe/twigbridge v0.8.1 requires illuminate/view 5.0.*|5.1.* -> satisfiable by illuminate/view[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8].
    - rcrowe/twigbridge v0.8.2 requires illuminate/view 5.0.*|5.1.* -> satisfiable by illuminate/view[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8].
    - don't install illuminate/view v5.0.0|don't install laravel/framework v5.2.3
    - don't install illuminate/view v5.0.22|don't install laravel/framework v5.2.3
    - don't install illuminate/view v5.0.25|don't install laravel/framework v5.2.3
    - don't install illuminate/view v5.0.26|don't install laravel/framework v5.2.3
    - don't install illuminate/view v5.0.28|don't install laravel/framework v5.2.3

**Comment by barryvdh** [comment]
Try 0.9.x
