### ISSUE TITLE
Dedicated tag for including views passed through Laravel's view process

### ISSUE THREAD

**Issue by kfriend** [rcrowe/TwigBridge#248]
I wanted to get an opinion on this, before creating a PR. 

Currently, when working within a Twig file, you have the ability to pull in other files with Twig's `include` tag. This is great, but these files aren't run through Laravel's view rendering process, which means the included file will be parsed as Twig, even if the file ends in a custom extension that you have a specific view parser configured to handle.

For example, I have added the `.vue.php` extension to Laravel's view factory, with PHP as its parser. If I try to include the view via Twig, then Twig will parse it. Since Vue and Twig both share `{{ }}` for output, Twig will potentially fail as it attempts to parse the `{{ }}` meant for Vue.

I'm currently working around this by including a function within the twigbridge config file:

``` php
'include_view' => [
    'callback' => function($view) {
        return view($view)->render();
    },
],
```

``` twig
{{ include_view('foo.bar') | raw }} {# includes foo/bar.vue.php #}
```

It would be nice to have a dedicated Twig tag which handles this. Something like:

``` twig

{# I'll parse the view with any configured parser #}

{% view 'foo.bar' %}

{% view 'foo.bar' {context: like_include_supports} %} {# Possibly with context support, just like include %}

{# But I'll render the view as Twig #}

{% include 'foo.bar' %}
```

**Comment by kwoodfriend** [comment]
Just saw #226, which is along the same lines, but thought I should provide an example of why I'm including a vue template within a twig template. 

To be clear, this would include the output of the parsed view. Not a Frankenstein combo of two view engines.

The example is simple:

```twig
// page.twig

... markup, body, etc

<script type="text/template" id="templateFooBar">
    {% include 'foo.bar' %} {# parse error #}
    {{ include_view('foo.bar') | raw }} 
</script>
```

```php
// foo/bar.vue.php

<component-name>
    <?php foreach ($var as $foo): ?>
         {{ something_that_twig_wont_like('<?= $foo ?>') }}
    <?php endforeach ?>
</component-name>
```
