### ISSUE TITLE
Sandboxed Properties

### ISSUE THREAD

**Issue by bytestream** [rcrowe/TwigBridge#265]
Accessing properties on an object of type ````Illuminate\Database\Eloquent\Model```` bypasses sandbox checks. See: https://github.com/rcrowe/TwigBridge/blob/master/src/Twig/Template.php#L116

As far as I can tell we just need to add the below to that function (line 121):
````php
if ($this->env->hasExtension('sandbox')) {
    $this->env->getExtension('sandbox')->checkPropertyAllowed($object, $item);
}
````

**Comment by bytestream** [comment]
If you agree I can submit a PR.

**Comment by barryvdh** [comment]
Okay

**Comment by barryvdh** [comment]
I'd rather strip that method override out completely, but not sure if that's possible.

**Comment by bytestream** [comment]
Sure. I'll do that if it's possible, otherwise I'll just submit the fix mentioned above.

**Comment by bytestream** [comment]
@barryvdh it seems like it might be possible to scrap the override. It falls to [#L462](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Template.php#L462) because Laravel models implement ````ArrayAccess````:

````php
public function offsetGet($offset)
{
    return $this->$offset;
}
````

That being said... [#L462](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Template.php#L462) doesn't support sandboxing array items. See [@fabpot](https://github.com/twigphp/Twig/issues/106#issuecomment-583737) and [PR#1863](https://github.com/twigphp/Twig/pull/1863)

Thoughts? I think given the Laravel docs (see below) explicitly say to access Model column values via property and not array we keep the override and add the sandbox code [#L526](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Template.php#L526).
````php
foreach ($flights as $flight) {
    echo $flight->name;
}
````
[Accessing Column Values](https://laravel.com/docs/5.2/eloquent)

**Comment by barryvdh** [comment]
I think the override was done because even though ArrayAccess is used, this doesn't work for all cases (isset with null values, relations which are not yet loaded etc). If we do that, we need to make a proper test case.

**Comment by bytestream** [comment]
Sorry, test case for what? Ensuring the sandbox works for model properties?
