### ISSUE TITLE
how to access helper functions?

### ISSUE THREAD

**Issue by maqboolkhan** [rcrowe/TwigBridge#272]
i want to use `csrf_field()` but i could not figure out how to use it?? 
and also want to ask how to access all these functions?
https://laravel.com/docs/master/helpers#method-csrf-field
thanks

**Comment by barryvdh** [comment]
Add them to the config file

**Comment by maqboolkhan** [comment]
Can u tell me.how kindly??

**Comment by barryvdh** [comment]
Put the function  in twigbridge.extensions.functions.

**Comment by maqboolkhan** [comment]
@barryvdh  in which file ?? did u mean in config/twigbridge.php ?

**Comment by barryvdh** [comment]
Yes
Op 29 mei 2016 07:48 schreef "maq" <notifications@github.com>:
