### ISSUE TITLE
FatalErrorException in Loader.php

### ISSUE THREAD

**Issue by geoom** [rcrowe/TwigBridge#291]
`Class TwigBridge\Twig\Loader contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_LoaderInterface::getSourceContext)`

It throws for 0.9.2 and 0.9.3 versions.

**Comment by barryvdh** [comment]
Which Twig version? 2?

**Comment by Smally1997** [comment]
https://github.com/twigphp/Twig/commit/21ecba8c44f3f64295448cbec0cd29d6ba12cadb I believe it's related to this issue.

**Comment by geoom** [comment]
I just put "TwigBridge: "~0.9.2" on `composer.json` file

**Comment by JC5** [comment]
I have this issue on a fresh Laravel installation. Is there a solution available?

**Comment by JC5** [comment]
Solved for the time being by forcing Twig 1.30.0 in my composer.json file.

`"twig/twig": "1.30.0",`

**Comment by cojok** [comment]
I still get the error for the versions "0.9.2" && "0.9.3". It is with a fresh Laravel installation.

**Comment by tyteen4a03** [comment]
I'm also on 0.9.3 and am getting this error.
