### ISSUE TITLE
remaining method

### ISSUE THREAD

**Issue by mountstone** [rcrowe/TwigBridge#302]
[Symfony\Component\Debug\Exception\FatalErrorException]
  Class TwigBridge\Twig\Loader contains 1 abstract method and must therefore be declared abstract or implement the remaining metho
  ds (Twig_LoaderInterface::getSourceContext)

**Comment by evertonto** [comment]
The problem is in the `TwigBridge \ Twig \ Loader` class that does not implement the following method, 

```
/**
     * {@inheritdoc}
     */
    public function getSourceContext($name)
    {
        $path = $this->findTemplate($name);

        return new \Twig_Source(file_get_contents($path), $name, $path);
    }

```
Could someone fix this?
