### ISSUE TITLE
Configure for Laravel 5.5 Package Auto-Discovery!

### ISSUE THREAD

**Issue by macwinnie** [rcrowe/TwigBridge#327]
Hi there – and thank you for TwigBridge, it's awesome!

Please configure it for using Laravel Package Auto-Discovery: https://laravel-news.com/package-auto-discovery (from Laravel 5.5)

All it needs are these entries into the `composer.json`-file:

```js
"extra": {
    "laravel": {
        "providers": [
            "TwigBridge\ServiceProvider"
        ],
        "aliases": {
            "Twig": "TwigBridge\\Facade\\Twig"
        }
    }
}
```

That would be great!

Thanks and cheers,
Martin

**Comment by davidhellmann** [comment]
Hm any news about that?
