### ISSUE TITLE
Laravel 5.7 Support

### ISSUE THREAD

**Issue by GlitterCakes** [rcrowe/TwigBridge#347]
The current version of TwigBridge doesn't allow the use of Laravel 5.7 based on required composer libraries. This package needs to support Laravel 5.7 to stay up to date.

**Comment by svenluijten** [comment]
5.7 isn't out yet though?

**Comment by svenluijten** [comment]
Yes @GlitterCakes, that just means the branch exists on the documentation website. [It has not been tagged yet](https://github.com/laravel/framework/releases), so it's not yet feature-locked, and things might change.

**Comment by mbardelmeijer** [comment]
Laravel 5.7 has just been released, saw the `composer.json` is already updated. Can a new release be tagged? :)

**Comment by GlitterCakes** [comment]
![image](https://user-images.githubusercontent.com/5402396/45053738-e5929680-b058-11e8-8ff0-7b7f85fde1f8.png)

**Comment by harrygulliford** [comment]
@barryvdh Could a new version please be tagged for Laravel 5.7 support? Thanks!

**Comment by fieryprophet** [comment]
If anyone wants to use a version of this with 5.7 support, I have a fork that works, just add my repo to your repositories array in composer.json

**Comment by barryvdh** [comment]
I tagged it
