### ISSUE TITLE
Packagist Versions Out of Date

### ISSUE THREAD

**Issue by ericdowell** [rcrowe/TwigBridge#361]
## Description
[Packagist](https://packagist.org/packages/rcrowe/twigbridge) lists the newest version of `v0.9` as `v0.9.10`, this version has a bug that forces `twig/twig` `~2.0` instead of maintaining `~1.30`.

Looking over tagged releases this issue was solved with the tagged version of `v0.9.11` and above.

## Solution
Please refresh the versions Packagist has listed.

## Logical Solution
Project `composer.json` will always have `twig/twig: ^1.37`:
```json
{
    "require": {
        "rcrowe/twigbridge": "^0.9",
        "twig/twig": "^1.37"
    }
}
```
Until the project is ready to upgrade to `twig/twig: ^2.0`

## Dirty Solution
Without Packagist being updated this will need to be changed to pull from source instead of `dist`. I was able to do this by adding this to my `composer.json`:
```json
{
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:rcrowe/TwigBridge.git"
        }
    ]
}
```
Last I finish by running `composer require rcrowe/twigbridge ^0.9.11` after deleting the `composer.lock`. I had to delete this file because other dependencies required `twig/twig ~2.0`.

**Comment by christophemassin** [comment]
Thanks, you found my issue ;)

**Comment by barryvdh** [comment]
I think they're tagged now.

**Comment by ericdowell** [comment]
@barryvdh Great, thank you. I am able to pull `v0.9.12` via `dist`.
