### ISSUE TITLE
Resize Filter?

### ISSUE THREAD

**Issue by creazy231** [rcrowe/TwigBridge#383]
I used the ` | resize(x, y)` filter within an old project some month ago.
Now I started a new project using laravel and twigbrige because I like the way twig works, but I tried to use the resize filter without success.

Is there any way to get the resize filter work using twigbridge?

**Comment by barryvdh** [comment]
Do you have a link to the filter? Not sure what it does?

**Comment by creazy231** [comment]
Timber for WordPress had such a function

**Comment by barryvdh** [comment]
Sorry not familiar with that. I would assume it would also need something like Glide to actually resize the images, or generate thumbnails

**Comment by creazy231** [comment]
Ok, realizing that this is an feature that does not come out of the box with twig.
Are there any plans adding this feature to TwigBridge or can we do this on our own? I think I have to create my own filter, right?
