### ISSUE TITLE
Call function from Model within Twig View returns null

### ISSUE THREAD

**Issue by creazy231** [rcrowe/TwigBridge#384]
Setup:
```
// User Model
class User extends Model
{
    ...
    public function someFunctionName() {
        return "TEST";
    }
}
```
```
// UserController
class UserController extends Controller
{
    public function index($sub = null) {
        $workers = User::all();
        return View::make('users/users', ['sub' => $sub, 'workers' => $workers]);
    }
}
```
```
// frontend.twig
{% for user in workers %}
        {{ dump(user.someFunctionName) }}
    {% endfor %}
```

The twig view (dump) returns `null` instead of `TEST`.
Whats wrong with my setup?

**Comment by barryvdh** [comment]
And with parentheses?

**Comment by creazy231** [comment]
Where should I put them?

**Comment by ndhan93** [comment]
user.someFunctionName => get property someFunctionName (your case)
user.someFunctionName() => call method someFunctionName (try this)

**Comment by creazy231** [comment]
Problem solved!
In my case I had two different User Models. One created by Laravel and one created by calling `php artisan code:models` and I didn't notice that Laravel was using the default User Model.

`user.someFunctionName()` works like expected. Thanks @ndhan93
