### ISSUE TITLE
Sandbox security escalation allowing users to read configuration

### ISSUE THREAD

**Issue by MaxKorlaar** [rcrowe/TwigBridge#388]
I recently discovered that when using the sandbox of Twig, the global variables added by Laravel are still available. By default, [the framework adds 'app' as a shared variable in the ViewServiceProvider](https://github.com/laravel/framework/blob/master/src/Illuminate/View/ViewServiceProvider.php#L52).

The problem with this is that although by itself app, as an instance of Application is quite harmless, the [Container instance which it inherits is not](https://github.com/laravel/framework/blob/master/src/Illuminate/Container/Container.php#L1279).
Twig's sandbox requires you to add the magic `__isset()` method to your classes in order to allow the sandbox' security policy to check if the method or property you are calling on your class is allowed. Laravel's Container class does not have this method, meaning that the `__get()` method can be used freely within the sandbox, regardless of the given security policy.

The Application class contains all instances for the application, including the configuration one. This configuration can be requested by simply calling `$application->config`, which will use the magic get method to fetch the config repository, which in turn allows you to request any value from the current configuration [as it implements ArrayAccess](https://github.com/twigphp/Twig/issues/2878) (unfortunately #362 doesn't fix this as it's not a Model).

## Tl;dr
You can read the configuration of any Laravel application from within Twig's sandbox by using the global app variable added by the framework itself. 

For example:
```twig
{% sandbox %}
    {% include(template_from_string(user_template) only %}
{% endsandbox %}
```
with `user_template` being the following:
```twig
The key is {{ app.config.app.key }}
```
would produce `The key is base64:your_app_key...`, while using the `config_get()` function would result in a Twig SecurityException being thrown as intended.

I don't suppose many users of this package are even using the sandbox or care about this issue but my proposed solution for now is to remove the `app` variable from the global context by either overriding it locally for your template or from within one of your app's ServiceProviders:
```twig
{% sandbox %}
    {% include(template_from_string(user_template) with {app: null } only %}
{% endsandbox %}
```
Or in a ServiceProvider:
```php
public function boot(): void {
    View::share('app', null);
}
```

Again, I don't know how big of an issue this really is with this package itself but I thought I'd leave it here anyway so it can either be documented somewhere or discussed.

**Comment by barryvdh** [comment]
Well we should probably fix that indeed. Not sure how though.

**Comment by bytestream** [comment]
@MaxKorlaar Thanks for logging this. If you have any thoughts on the below, please comment :)

@barryvdh We'd have to handle it here - https://github.com/rcrowe/TwigBridge/blob/2054abdbd8dcde573cd86d8d3856873e2388d47b/src/Node/GetAttrNode.php#L132

It's been a while since I looked at this but could we not just change `is_a($object, 'Illuminate\Database\Eloquent\Model')` to `$object instanceof ArrayAccess`. The `is_a` code has been here pretty much sicne the beginning. I've just copied it around in my previous PRs.

Not sure why https://github.com/twigphp/Twig/pull/1863 was rejected / closed which did what I'm suggesting. Possibly - https://github.com/twigphp/Twig/issues/106#issuecomment-583737

**Comment by bytestream** [comment]
See https://github.com/rcrowe/TwigBridge/pull/398

**Comment by bytestream** [comment]
I've decided to just override `base_template_class` when I'm using a security policy. 

```php
abstract class Template extends \Twig\Template
{
    /**
     * {@inheritdoc}
     */
    public function display(array $context, array $blocks = [])
    {
        \Twig\Template::display($context, $blocks);
    }
}
```

**Comment by ovp87** [comment]
Any solution to this issue? all attempts at fixing it seems to have been reverted.
