### ISSUE TITLE
ErrorExtension to handle form errors in TwigBridge

### ISSUE THREAD

**Issue by felixdorn** [rcrowe/TwigBridge#389]
Hello!

I wrote a small extension on my app to handle errors using a syntax like that

```twig
{% error "errorKey" %}
       <strong>{{ message }}</strong>
{% enderror %}
```

I don't want to copy/paste it for my next project and I think it could be useful.

Could I make a PR ? What do you think ?

**Comment by barryvdh** [comment]
Maybe you can post the code for reference for others?

**Comment by felixdorn** [comment]
Unfortunately, I don't have it anymore but I would have done so otherwise, of course!
