### ISSUE TITLE
Twig_Extension_Escaper::addSafeClass() not available with Twig <2.11.0

### ISSUE THREAD

**Issue by kiding** [rcrowe/TwigBridge#399]
https://github.com/rcrowe/TwigBridge/blob/542f4148dfbdf484c3ee17f094374fefe4503f47/src/ServiceProvider.php#L234

Since `Twig_Extension_Escaper::addSafeClass()` was introduced with Twig 2.11.0 https://github.com/twigphp/Twig/commit/b18733bce02ddfbcb4c99051a253cfccc2f17740,  when used with <2.11.0 "Call to undefined method Twig_Extension_Escaper::addSafeClass()" error gets invoked.

https://github.com/rcrowe/TwigBridge/blob/259202354d9f38ba58352a0b67b85cb5bff72d92/composer.json#L18

The composer.json requirement should be changed to "^2.11.0" or something else.

**Comment by barryvdh** [comment]
Done https://github.com/rcrowe/TwigBridge/commit/dd018dae10addee5ef03e437546149fd1fa2e12b
