### ISSUE TITLE
View::composer not working v.0.14.0

### ISSUE THREAD

**Issue by mygomel** [rcrowe/TwigBridge#425]
I am using the construct in ServiceProvider:
```
        View::composer(['blocks.MetaTags.MetaTags__Meta', 'blocks.MetaTags.MetaTags__Script'], function (ViewTemplate $view) {
            $view->with([
                'assetTimestamp' => ServiceHelper::getAssetDate(),
            ]);
        });
```
After updating from v0.12.4 to v0.14.0 View::composer no longer supplies variables to the template

**Comment by adrienne** [comment]
I am having an issue that may be related, @rcrowe -- in my case it's that I used to be able to invoke `View::compose()` on a layout template and it would apply to everything that `{% extends %}` it, and that is no longer working.

**Comment by daanadriaan** [comment]
Same here! @mygomel Did you find a work around already?

**Comment by EgorGruzdev** [comment]
You need to enable the extension for it to work: \TwigBridge\Extension\Laravel\Event::class

**Comment by mygomel** [comment]
> You need to enable the extension for it to work: \TwigBridge\Extension\Laravel\Event::class
Thanks, it helped, the config is different in the new version, you need to make changes when updating
