### ISSUE TITLE
I installed TwigBridge, however it can't figure out view.engine.resolver

### ISSUE THREAD

**Issue by niterain** [rcrowe/TwigBridge#67]
However, everytime I run the php artisan dump-autoload command, I get a {"error":{"type":"ReflectionException","message":"Class view.engine.resolver does not exist","file":"\/www\/sites\/www.complete.com\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php","line":303}}

I am using Laravel 4.0.9

**Comment by renalpha** [comment]
@niterain 
What was your solution to this problem?

**Comment by niterain** [comment]
Sorry, renalpha.

I probably should have listed the fix here.  Sorry, I don't recall how I fixed it.
