### ISSUE TITLE
Add custom tests

### ISSUE THREAD

**Issue by Anahkiasen** [rcrowe/TwigBridge#73]
I wanted to add a custom test to Twig but I can't seem to find how as when I do `$app['twig']->addTest()` I get a `Unable to add test "mytest" as extensions have already been initialized.`.

Is there any way to extend Twig that way with the current implemenation ?

**Comment by bytestream** [comment]
Sorry to reopen this, but how do we achieve this in the latest release? ````\Twig::addTest```` after initialization results in the same error mentioned above.

I see events were removed:

> The TwigBridge events are removed. Similar results can be achieved by simply using the Twig facade or IoC bindings

https://github.com/rcrowe/TwigBridge/blob/78a4b7da75042660258a3269751c259eee81c34a/UPGRADE.md
