### ISSUE TITLE
Issue with Laravel Theme Package

### ISSUE THREAD

**Issue by garyblankenship** [rcrowe/TwigBridge#85]
This seems to have a conflict with the Laravel Theme package.
https://packagist.org/packages/bigecko/laravel-theme

**Comment by svenluijten** [comment]
Is this still relevant? Is Laravel 4 even still supported @barryvdh? Just going through old issues to see if there's anything I can help with 🙂

**Comment by garyblankenship** [comment]
no longer applicable
